spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
      routes:
        - id: promotion-route
          uri: lb://service-promotion
          predicates:
            - Path=/coupons/**
        - id: auth-learning
          uri: lb://service-learning
          predicates:
            - Path=/learning/**
        - id: auth-route
          uri: lb://service-auth
          predicates:
            - Path=/auth/**
        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                pattern: /search
            - name: Query
              args:
                param: q
                regexp: haha
#            - Vip=user,leifengyang
            - name: Vip
              args:
                param: user
                value: leifengyang
          order: 10
        - id: order-route
          uri: lb://service-order
          predicates:
            - name: Path
              args:
                pattern: /api/order/**
                matchTrailingSlash: true
          filters:
            - RewritePath=/api/order/?(?<segment>.*),/$\{segment}
            - OnceToken=X-Response-Token, uuid
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*),/$\{segment}
          order: 2
      default-filters:
        - AddResponseHeader=X-Response-abc, 123
