server:
  port: 10001
spring:
  application:
    name: service-auth
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  profiles:
    include: datasource,mybatisplus